# Location to store checkpoints
seed: 0

device : "cuda"
bf16: False
epochs: 200

data:
  num_workers: 4
  batch_size: 512

net:
  compile: False
  vocab_size: 512
  context_size: 50
  n_layer: 3
  n_head: 6
  n_embd: 120
  dropout: 0.0
  bias: False
  mlp: True

optimizer:
  learning_rate: 0.0003
  weight_decay: 0.1
  beta1: 0.9
  beta2: 0.95
  grad_clip: 1.0

  decay_lr: True
  warmup_iters: 200
  min_lr: 0.000006

log: 
  eval_interval: 5000
  log_interval: 50
