seed: 0

# Properties of the prompt
n_alphabets: 26        # Total number of tokens "a-z" + " "
seq_len: 6              # Length of tokens in data prompt
ndocuments: 100000      # Number of training documents
neval_documents: 10000  # Number of evaluation documents
with_replacement: False # Whether to sample strings with replacement

function:
  n_functions: 6  # Number of maximum functions per composition
  repeat: False   # Repeat functions for every step of composition
  type: 'uniform'
  split:
    strategy: 'combination_6' # default choice replaced by command line argument for data generation
    
    